inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - strictest.yml

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
